version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    command: ["live-server", "src", "--host=0.0.0.0", "--port=8080"]
